name: Rust Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: rust-build/rust-build.action@v1.4.5
    - env:
        RUSTTARGET: "aarch64-none-linux-gnu-gcc"
        MINIFY: true
    - name: Build
      run: cargo build -r --verbose
